# Generated by Django 4.1.7 on 2023-05-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('zip_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=40)),
                ('quarter', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('amount', models.IntegerField(default=1)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
                ('id_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.data')),
                ('id_product', models.ManyToManyField(to='dashboard.product')),
            ],
        ),
    ]
