# Generated by Django 4.1.7 on 2023-05-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='create_date',
        ),
    ]
