# Generated by Django 4.1.7 on 2023-05-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=30)),
                ('descriptions', models.TextField()),
                ('font_category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProductShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(db_index=True, max_length=40)),
                ('slug', models.SlugField(max_length=200)),
                ('descriptions', models.TextField()),
                ('average_grade', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('image_product', models.ImageField(upload_to='media/image_product/%Y/%m%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('promotion', models.BooleanField(default=False)),
                ('available_product', models.BooleanField(default=True)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryproduct')),
            ],
            options={
                'index_together': {('id', 'slug')},
            },
        ),
    ]
