# Generated by Django 4.1.7 on 2023-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
