# Generated by Django 4.1.7 on 2023-05-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('paid_to', models.BooleanField(default=False)),
                ('customer_first_name', models.CharField(max_length=80)),
                ('customer_last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=270)),
                ('zip_code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElementInCustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productshop')),
            ],
        ),
    ]
